# Generated by Django 5.0.3 on 2024-05-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_for_product',
            field=models.ImageField(blank=True, null=True, upload_to='product_media/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
