# Generated by Django 5.0.3 on 2024-05-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_for_product_delete_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='c',
        ),
    ]
