# Generated by Django 5.0.3 on 2024-06-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxingCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('punch_types', models.CharField(max_length=100)),
                ('sparring_partner_required', models.BooleanField(default=False)),
            ],
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='CardioCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('intensity_level', models.CharField(max_length=100)),
                ('equipment_needed', models.CharField(max_length=100)),
            ],
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='CyclingCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('terrain_type', models.CharField(max_length=100)),
                ('bike_type', models.CharField(max_length=100)),
            ],
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='KarateCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('belt_colors', models.CharField(max_length=100)),
                ('kata_required', models.BooleanField(default=True)),
            ],
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='MeditationCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('meditation_style', models.CharField(max_length=100)),
                ('relaxation_techniques', models.CharField(max_length=100)),
            ],
            bases=('courses.course',),
        ),
    ]
