# Generated by Django 5.0.3 on 2024-04-29 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasts', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fast',
            options={},
        ),
        migrations.AddField(
            model_name='fast',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='fast', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fasts.fast')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
