# Generated by Django 5.0.3 on 2024-06-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100, verbose_name='Дата')),
                ('time', models.TimeField(max_length=5, verbose_name='Время')),
                ('event', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписании',
            },
        ),
    ]
